### ISSUE TITLE
spawn chance not working

### ISSUE THREAD

**Issue by maclarens** [Psykotikism/Mutant_Tanks#121]
This "Special Chance" is not working i try many times, he only on or off!

**Comment by Psykotikism** [comment]
Show me how you use it.

**Comment by Psykotikism** [comment]
Try `2.0` not `2` because the setting only accepts `float` values.

**Comment by Psykotikism** [comment]
I'll look into the issue when I get a chance.

**Comment by Psykotikism** [comment]
Okay I looked into this. What's happening is that Icy Smoker is being listed as a backup type. The plugin then cycles through any available types. When nothing else is available, the plugin then picks through the backup list. So the 2% spawn chance is being read properly, but it's being ignored because the plugin can't find any other available mutant types to spawn.

If you want me to look further into this, you'll have to share your entire config file with me.

**Comment by Psykotikism** [comment]
Just the main config file in addons/sourcemod/data/mutant_tanks folder.

Have you updated to the latest version (v9.2)? No one else has reported any crashes for MT recently.

**Comment by Psykotikism** [comment]
I haven't been able to replicate the crashes you're talking about and nobody else has reported it so I can't really do anything about that.

As for your `Special Chance` issue, I would just chalk it up to the plugin having nothing else to choose from so it spawns that particular mutant smoker.

The way the mutant spawner works is that it cycles through all the mutant types and puts them in a backup list. Then it chooses a random mutant type to spawn. If none are available it will choose from the backup list. I believe that's what's happening in your case. It's working as intended.

**Comment by Psykotikism** [comment]
This is how the current spawner works:
```cpp
if mutant_type meets all conditions
	- add to backup list

if mutant_type spawn chance <= X% and meets all conditions
	- add to cycle list

if mutant_type has not spawned yet and meets all conditions
	- add to available list

...

if available list is empty
	- use cycle list
else if available list has mutant types
	- use available list

if available list and cycle list are empty
	- use backup list
```
With the current logic, even a mutant type with 1% chance of spawning can still spawn IF the other mutant types cannot spawn.

I think what you are asking for is a set of backup lists that separates mutant types based on their individual probabilities, like this:
```cpp
if available list and cycle list are empty
	- use backup probability lists
		- 91-100%
		- 81-90%
		- 71-80%
		- 61-70%
		- 51-60%
		- 41-50%
		- 31-40%
		- 21-30%
		- 11-20%
		- 1-10%
		- 0.1-0.99%
```
I'll see what I can do since this is definitely doable.

**Comment by Psykotikism** [comment]
Alright, the new logic for the spawner will be added in the next update.
